sudo: false

language: php

php:
    - 7.0
    - 7.1
    - nightly
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - LARAVEL_VERSION="5.3.*"
    - LARAVEL_VERSION="5.3.*" COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL_VERSION="5.4.*"
    - LARAVEL_VERSION="5.4.*" COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL_VERSION="dev-master"

matrix:
    fast_finish: true

    allow_failures:
        - php: hhvm
        - php: nightly
        - env: LARAVEL_VERSION="dev-master"

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [ "${LARAVEL_VERSION}" != "" ]; then composer require --no-update "laravel/laravel:${LARAVEL_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
